-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 20:18:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema telegramboot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema telegramboot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `telegramboot` DEFAULT CHARACTER SET utf8 ;
USE `telegramboot` ;

-- -----------------------------------------------------
-- Table `telegramboot`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telegramboot`.`requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requests` (
  `request` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(2000) NOT NULL,
  `response` BLOB NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`request`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

